### ISSUE TITLE
All chairs are missing textures

### ISSUE THREAD

**Issue by taco360** [Samlegamer/Macaw-s-Furnitures-Compat#1]
![image](https://user-images.githubusercontent.com/61074066/198748130-cbc7e8fa-ba20-43b2-94e3-832db624ce59.png)
![image](https://user-images.githubusercontent.com/61074066/198748351-af978f99-dac1-4f8e-8f58-832791426dd9.png)

Update: 1.18.2
Mod: Macaw's Furnitures - Biomes O' Plenty
Mod Version: 1.0

All chairs appear with missing preview textures in menus. Upon placement, the hitbox is correctly rendered but the texture is not.

**Comment by Samlegamer** [comment]
fixed in 1.18.2-1.1
