### ISSUE TITLE
All chairs are missing textures

### ISSUE THREAD

**Issue by TomboWombo** [Samlegamer/Macaw-s-Furnitures-Compat#2]
Hi there! I'm experiencing the same issue as Taco360 in the previous issue, however I'm running on 1.19.2. All BOP chairs are missing their textures but are still functional.

Update: 1.19.2
Mod: Macaw's Furnitures - Biomes O' Plenty
Mod Version: 1.0
Biomes O' Plenty version: BiomesOPlenty-1.19.2-17.1.1.162

**Comment by Samlegamer** [comment]
fixed in 1.19.2-1.1
