### ISSUE TITLE
Missing Item textures.

### ISSUE THREAD

**Issue by Rambonata** [Samlegamer/Macaw-s-Furnitures-Compat#4]
Hello, I have a similar issue to #1 and #2 but a larger number of items are missing. (Minecraft 1.18.2)
![image](https://user-images.githubusercontent.com/29131003/222985419-50d4b1f4-6d05-4ccf-a96f-aad672308195.png)

I saw that the issue is supposedly fixed in 1.1, but i don't see that version posted anywhere. Is it still indev?

**Comment by Samlegamer** [comment]
It is being fixed, the new version of Macaw's Furnitures to many changes in the jsons take mcwfurnitures 3.0.2 until the problem is solved.

https://www.curseforge.com/minecraft/mc-mods/macaws-furniture/files/4018178

**Comment by Samlegamer** [comment]
corrected in the latest versions
