### ISSUE TITLE
crash with macaws furniture 3.2.0

### ISSUE THREAD

**Issue by superdude808** [Samlegamer/Macaw-s-Furnitures-Compat#6]
[crash-2023-08-30_19.36.21-client.txt](https://github.com/Samlegamer/Macaw-s-Furnitures-Compat/files/12475193/crash-2023-08-30_19.36.21-client.txt)

seems both mods that add compat for macaws furniture need to be updated despite what it says at the top of the crash log which confused me for like nearly 10 mins before I thought about reading through the whole crash log which I should of done from the begining

P.S. You do good work most wouldn't be bothered to make nice things like these compat mods

**Comment by Samlegamer** [comment]
fixed in mcwfurnituresbop-1.19.2-1.3

**Comment by superdude808** [comment]
sorry to be a bother but the issue was for both bop compat and byg compat
[crash-2023-08-31_09.52.25-client.txt](https://github.com/Samlegamer/Macaw-s-Furnitures-Compat/files/12481417/crash-2023-08-31_09.52.25-client.txt)

**Comment by superdude808** [comment]
I should of uploaded both crash logs at once sorry for the inconvenience

**Comment by liangmoe** [comment]
same issue here but im on fabri
[crash-2023-08-31_19.40.42-client.txt](https://github.com/Samlegamer/Macaw-s-Furnitures-Compat/files/12485881/crash-2023-08-31_19.40.42-client.txt)
c version

**Comment by liangmoe** [comment]
Newest version fix the issue, thanks a lot
