### ISSUE TITLE
1.18.2-1.2 Crash Report (Macaw BOP furniture)

### ISSUE THREAD

**Issue by MiniHumon** [Samlegamer/Macaw-s-Furnitures-Compat#7]
Game crashed with this log:

Macaw's Furnitures - BOP (mcwfurnituresbop) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: 'void com.mcwfurnitures.kikoz.objects.counters.Counter.<init>(net.minecraft.world.level.block.state.BlockState, net.minecraft.world.level.block.state.BlockBehaviour$Properties)'

Crash said report it to this github, so here I am

**Comment by MiniHumon** [comment]
Keeps telling me it's missing the cherry top counter

**Comment by Samlegamer** [comment]
tested with new version mcwfurnituresbop-1.18.2-1.3 ?

**Comment by MiniHumon** [comment]
Everything works now, thank you. Also, love the mod series keep up the good work
