### ISSUE TITLE
Problem with axe mining speed

### ISSUE THREAD

**Issue by Cardinal-23** [Samlegamer/Macaw-s-Furnitures-Compat#8]
With this mod installed, all axes mine (Wood Logs and Pumpkins/Melons only blocks tested) at the same speed as if you were using your fist to punch the blocks.

**Comment by Samlegamer** [comment]
Mods version ?

**Comment by Cardinal-23** [comment]
The latest Forge version for 1.20.1, released Aug 31 2023. File name: mcwfurnituresbop-1.20-1.0

**Comment by Dimiral** [comment]
Same problem
Version: 1.20-1.0

**Comment by Samlegamer** [comment]
mcwfurnituresbop-1.20-1.1
